SOURCES = problemset1.ml
PACKS = universe
INCDIRS = ~/.cs1103/lib/ocaml/
#INCDIRS = /home/vagrant/.cs1103/lib/ocaml/
LIBS = cs1103 assert
RESULT = problemset1
OCAMLMAKEFILE = ~/.opam/4.03.0/lib/ocaml-makefile/OCamlMakefile
include $(OCAMLMAKEFILE)

